title: Uncanny Recursions
description: Uncanny recursions that happen every now and then!
author: Rafay Aleem
github: https://github.com/mrafayaleem
about: I'm Programmer for Python & Django. I've made quite a few web apps, especially on Django.
disqus_shortname: stackproblems
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/mrafayaleem/"
    - icon: fa-twitter
      link: "https://twitter.com/mrafayaleem"
    - icon: fa-stack-exchange
      link: "https://stackoverflow.com/users/569085/rafay"
    - icon: fa-github
      link: "https://github.com/mrafayaleem"

share:
  twitter_username: mrafayaleem
#  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://mrafayaleem.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
