# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Uncanny Recursions
tagline:          ''
description:      'Currently Software Engineer at <a href="https://dubai.dubizzle.com" target="_blank">dubizzle</a>. Living and enjoying life in Dubai, UAE. Huge nerd who likes playing guitar and is a Clapton fan.</a>'
url:              http://mrafayaleem.com

author:
  name:           'Mohammad Rafay Aleem'
  url:            https://twitter.com/mrafayaleem

paginate:         5

# Custom vars
version:          2.0.0

files:
  resume:         /static_files/mrafayaleem.pdf

github:
  repo:           https://github.com/mrafayaleem

social:
  linkedin:       https://ae.linkedin.com/in/mrafayaleem
  twitter:        https://twitter.com/mrafayaleem

gems :
  - jekyll-paginate
